grpc-mqtt.cabal, src/Network/GRPC/MQTT/Client.hs, src/Network/GRPC/MQTT/Core.hs, src/Network/GRPC/MQTT/Logging.hs, src/Network/GRPC/MQTT/RemoteClient.hs, test/Test.hs, test/Test/Helpers.hs
Added simple logging infrastructure and various log messages. 
A `Logger` type carries a logging function and verbosity and this is passed to functions as needed. This works just fine for now. If the code grows and threading this `Logger` around becomes difficult, then we can look at doing something like using `ReaderT`.
=> Add logging 

fourmolu.yaml, gen/Proto/Mqtt.hs, gen/Proto/Test.hs, grpc-mqtt.cabal, nix/overlays/haskell-packages.nix, proto/mqtt.proto, proto/test.proto, src/Network/GRPC/MQTT.hs, src/Network/GRPC/MQTT/Client.hs, src/Network/GRPC/MQTT/Core.hs, src/Network/GRPC/MQTT/Logging.hs, src/Network/GRPC/MQTT/RemoteClient.hs, src/Network/GRPC/MQTT/Sequenced.hs, src/Network/GRPC/MQTT/TH/Client.hs, src/Network/GRPC/MQTT/TH/Proto.hs, src/Network/GRPC/MQTT/TH/RemoteClient.hs, src/Network/GRPC/MQTT/Types.hs, src/Network/GRPC/MQTT/Wrapping.hs, test/Test.hs, test/Test/GRPCServers.hs, test/Test/Helpers.hs, test/Test/ProtoClients.hs, test/Test/ProtoRemoteClients.hs
This PR adds support for client streaming gRPC requests. This was a pretty invasive change that necessitated some significant refactoring (which snowballed to include some less significant refactoring as well...). Most of the substantive changes are in the modules `Network.GRPC.MQTT.Client` and `Network.GRPC.MQTT.RemoteClient`
Other key changes:
- Response topics are no longer sent along with message requests and the pre-established response topic pattern will be used: `<baseTopic>/grpc/session/<sessionId>`. This helps to normalize the bi-directional communications, but should also give a significant performance improvement. The remote client can now subscribe to all topics at once on initialization instead of for each incoming request.
- The RemoteClient `Session`s have been overhauled …
=> Client Streaming

README.md, gen/Proto/Mqtt.hs, grpc-mqtt.cabal, proto/mqtt.proto, src/Network/GRPC/MQTT/Client.hs, src/Network/GRPC/MQTT/RemoteClient.hs, src/Network/GRPC/MQTT/Sequenced.hs, src/Network/GRPC/MQTT/Wrapping.hs
- Refactored wrapping/unwrapping functions to be less haphazard. 
- MetadataMap is now stored as a list of key/value pairs instead of the proto3 `map` type. This was mostly done so that the generated Haskell type more closely matches the expected semantics, but also saves us from needing to base64 encode the keys.
- Now there is only one `MQTTResponse` message type that is used universally for all stream types.
- New `disconnectMQTTGRPC` function exported to pair with `connectMQTTGRPC`.
=> Protobuf types refactor

src/Network/GRPC/MQTT/Logging.hs, src/Network/GRPC/MQTT/RemoteClient.hs
This exposes another `runRemoteClient` that let's a consumer create their own client. This enables whatever networking shenanigans they need in their environment.
=> Allow users to create their own client

src/Network/GRPC/MQTT/Client.hs, src/Network/GRPC/MQTT/RemoteClient/Session.hs
RabbitMQ does not support dots in topic names. Fully qualified service
names usually have dot characters in it and need to be escaped before
using as a topic name in the client and unescaped in the remote client.
I used hyphen as a replacement because hyphens are not valid
identifier characters according to protobuf specification.
=> Escape dots in service names

grpc-mqtt.cabal, src/Network/GRPC/MQTT/TH/Client.hs, src/Network/GRPC/MQTT/TH/Proto.hs, src/Network/GRPC/MQTT/TH/RemoteClient.hs, src/Proto3/Suite/DotProto/Internal/Compat.hs
Starting with proto3-suite 0.5.0, the initial character of
a service method names is no longer forced to uppercase.
=> Support proto3-suite 0.5.0 and later.

nix/overlays/haskell-packages.nix
`test.proto` was removed but the nix configuration was not updated accordingly.
=> Remove reference to test.proto

proto/README.md, proto/haskell/grpc/mqtt.proto, proto/haskell/grpc/mqtt/clevel.proto, proto/haskell/grpc/mqtt/option.proto
Adds a few new protos exposing the library's options and a `CLevel` enum that can be used with `protoc`
=> Add files exposing protobuf options. 

grpc-mqtt.cabal, nix/overlays/haskell-packages.nix, nix/packages/grpc-haskell.nix, nix/packages/proto3-suite.nix, nix/packages/proto3-wire.nix, nix/packages/word-compat.nix, src/Network/GRPC/MQTT/Message/Packet.hs, test/Proto/Service.proto, test/Test/Network/GRPC/MQTT/Message/Packet.hs, test/Test/Service.hs
Avoids allocating and freezing a `MVector` of packets before each packet is published. This should help reduce GC pressure in larger services.
=> Factor MVector allocation out of packetization

grpc-mqtt.cabal, src/Network/GRPC/MQTT/RemoteClient.hs, src/Network/GRPC/MQTT/RemoteClient/Session.hs
Currently, RemoteClient's watchdog only waits 11 seconds for a heart
beat before killing the session while the Client sends a heart beat
every 10 secs. Thus, the RemoteClient ends up terminating requests
aggressively while the Client continues to wait. The fix increases the
RemoteClient timeout value to 3x the Client value so that there is a
sufficient window for delayed heart beats.
=> Increase watchdog timeout

grpc-mqtt.cabal, src/Network/GRPC/MQTT/Message/Packet.hs, test/Test.hs, test/Test/Network/GRPC/MQTT/Message.hs, test/Test/Service.hs
This PR replaces the `forConcurrently_` usage in `makePacketSender` with `replicateConcurrently_` and a semaphore. This change impacts how threads are used in the `makePacketSender` function. Previously, using `forConcurrently_` would create a new thread for each packet to be published, which performs well but incurs a lot of GC pressure due to each thread being allocated an initial GHC stack size and subsequent stack segments extensions to execute serialization and publishing. 
Running the `"LongBytes"` tests with `-N4 -hT` shows that `19mb` need to be allocated to the GHC stack to split the `BytesResponse` message into packets with `forConcurrently_`:   
Most of this is excess stack segment allocations that are never used. The changes in this PR avoids the excess allocations for GHC …
=> Reuse threads in packet sender 

test/Test/Service.hs
This PR fixes an issue in the implementation of "LongBytes" causing a timeout error discovered by #40.
=> Fix "LongBytes" Test Case

default.nix, shell.nix, src/Network/GRPC/MQTT/Message/Response.hs, src/Network/GRPC/MQTT/RemoteClient.hs, src/Network/GRPC/MQTT/TH/Proto.hs, src/Network/GRPC/MQTT/TH/RemoteClient.hs, src/Network/GRPC/MQTT/Types.hs, src/Network/GRPC/MQTT/Wrapping.hs
`RemoteClient` decodes protobuf messages received from the gRPC service to a Haskell type to immediately encode it back to protobuf and send it to MQTT. This consumes a significant amount of memory and CPU.
This change removes the encoding/decoding logic completely from the `RemoteClient`. Instead, we pass the protobuf encoded bytes directly between the `Client` and the remote gRPC service. Any serialization errors will be handled by them instead of the `RemoteClient`.
=> Remove ProtoBuf encoding/decoding from RemoteClient

src/Network/GRPC/MQTT/Core.hs, src/Network/GRPC/MQTT/Message/Packet.hs, src/Network/GRPC/MQTT/Message/Request.hs, src/Network/GRPC/MQTT/Message/Response.hs, src/Network/GRPC/MQTT/Message/Stream.hs, src/Network/GRPC/MQTT/RemoteClient/Session.hs, test/Test/Network/GRPC/MQTT/Message/Gen.hs, test/Test/Network/GRPC/MQTT/Message/Packet.hs
This PR fixes a bug in how packets are split that would cause the size of serialized packets to be exceed the maximum packet size by a few bytes.
The problem occurred when serializing packets with a payload equal to the maximum packet size. The packet fields `position` and `npackets` were not accounted for when splitting a `ByteString` into packets. This mean't that a packet with a payload length equal to the max packet size would exceed the maximum packet size after the bytes from `position` and `npacket` fields were included in the serialized message.
The bug can be observed by running the "LongBytes" test, which has a maximum packet size of 128, but was publishing messages with a length of 128,008 bytes.
```
0000000000: Sending PUBLISH to Test.Client (d0, q1, r0, m310, …
```
=> Prevent wire serialization from exceeding max packet size 

proto/haskell/grpc/mqtt/option.proto
Removes `optional` from `option.proto` for compatibility with `proto3-suite`.
=> Remove `optional` from `option.proto`

nix/packages/grpc-haskell-core.nix, nix/packages/grpc-haskell.nix, src/Network/GRPC/HighLevel/Orphans.hs, src/Network/GRPC/MQTT/Option.hs, src/Network/GRPC/MQTT/Option/Batched.hs, src/Network/GRPC/MQTT/Option/CLevel.hs, test/Test/Network/GRPC/MQTT/Option/Gen.hs, test/Test/Service.hs
This PR removes slight differences between the encoding and decoding side of `ProtoOptions` wire serialization functions. Specifically, using [`packedVarints`](https://github.com/awakesecurity/grpc-mqtt/blob/4dbf3df65be462e31a125a4993fda51ce911b728/src/Network/GRPC/MQTT/Option.hs#L217) to parse serialized `ProtoOption` messages while [`packedVarintsV`](https://github.com/awakesecurity/grpc-mqtt/blob/4dbf3df65be462e31a125a4993fda51ce911b728/src/Network/GRPC/MQTT/Option.hs#L196) was used to serialize the original messages.
This work builds off of #48.
=> Fix `ProtoOptions` wire serialization

nix/packages/grpc-haskell-core.nix, nix/packages/grpc-haskell.nix
Upgrade pinned revision for the gRPC-haskell and gRPC-haskell-core packages. The new revision includes the changes made by [`gRPC-haskell/142`](https://github.com/awakesecurity/gRPC-haskell/pull/142). These changes add helper functions `startGRPC` and `stopGRPC` that can be used to clean up test suite in `grpc-mqtt`.
=> Upgrade pinned rev for gRPC-haskell(-core)

grpc-mqtt.cabal
This PR adds a missing change #58 correcting the `version` field in`grpc-mqtt.cabal` to `1.0.0`. The previous `0.1.0.0` did not use semantic versioning or match the version specified in `@since` haddock annotations.
=> Fix cabal version `0.1.0.0 -> 1.0.0`

.github/workflows/ci.yaml
https://github.com/cachix/cachix-action/issues/137
=> In CI, pin nix version due to regression in 2.14

src/Network/GRPC/MQTT/Logging.hs, src/Network/GRPC/MQTT/RemoteClient.hs, src/Network/GRPC/MQTT/RemoteClient/Session.hs, test/Test/Service.hs
- New function `useSessionId` which modifies a `Logger` to prefix log messages with the session id so that we can associate log messages with a particular session
- The RemoteClient now logs general information about the incoming requests and responses at the `Info` log level
- The request/response message bodies are still limited to the `Debug` log level
=> Adds more informative logging

test-files/mqtt-broker.conf
These options are for using mosquitto as a bridge between multiple MQTT brokers, which doesn't seem applicable here. I don't think it was causing any issues other than adding some noise the the test logs.
=> Remove mosquitto bridge configuration

src/Network/GRPC/MQTT/Message/Packet.hs, test/Test/Network/GRPC/MQTT/Message/Packet.hs
A deadlock could occur if we received the last packet twice before receiving all the other packets as it would be blocked on `putTMVar` since nothing ever takes from this `TMVar`.
Also added a test which sends every packet of a message twice in a random order to catch these kinds of errors in the future.
=> Fix deadlock and add new test case for out of order duplicate packets

nix/packages/grpc-haskell-core.nix, nix/packages/grpc-haskell.nix
This PR updates the pinned `grpc-haskell` and `grpc-haskell` revisions to https://github.com/awakesecurity/gRPC-haskell/commit/d20c20d63c170b5eaf5725f03f7b7060352af402. This revision includes the fix for a initial metadata memory leak in the C core of [gRPC-haskell](https://github.com/awakesecurity/gRPC-haskell).
=> Update `grpc-haskell` and `grpc-haskell-core` pins to revision `d20c20d`

src/Network/GRPC/MQTT/Client.hs
Currently, the first heartbeat message comes out immediately after sending the request. Sometimes it can even be delivered before the request is received.
There is plenty of buffer for the heartbeat message to delay one cycle before sending. This has the additional benefit of often not needing to send a heartbeat at all for quick requests.
=> Delay sending of first heartbeat message

grpc-mqtt.cabal, test/Test.hs, test/Test/Suite/Config.hs
This allows running the test suite with other MQTT brokers (e.g. AWS)
=> Support supplying TLS credentials in test-suite

cabal.project, flake.lock, grpc-mqtt.cabal, nix/packages/net-mqtt.nix, src/Network/GRPC/MQTT/Core.hs
This change adds two new fields to the `MQTTGRPCConfig` data type:
- `_pingPeriod`; and,
- `_pingPatience`
=> Update `MQTTGRPCConfig` to work with upstream `MQTTConfig` changes in `net-mqtt-0.8.3.0`

Setup.hs
It used to live in `Distribution.Simple.Program.Types` but in Cabal 3.10 the implementation was moved one module higher.
Since it used to be reexported there in older releases, it should be backwards compatible
=> Fix import of `simpleProgram` with Cabal 3.10
